apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
namespace: instavote
replicas: 
  - name: vote
    count: 9
images: 
  - name: schoolofdevops/vote
    newTag: v4
namespace: instavote
